# Generated by Django 4.1 on 2022-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keith_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('player_level', models.IntegerField(default=0)),
                ('player_hp', models.IntegerField(default=0)),
                ('player_attack_points', models.IntegerField(default=0)),
            ],
        ),
    ]
